In [62]:
import pandas as pd
import numpy as np

In [63]:
embeddings_per_enzyme = {}
enzyme_list = []

In [64]:
with np.load('output_5000.npz', allow_pickle=True) as data:
    for a in data:
        x = data[a].item()
        embeddings_per_enzyme[a] = x['avg']
        enzyme_list.append(a)

In [65]:
all_data = pd.DataFrame()

In [66]:
all_data['Name'] = enzyme_list

In [67]:
isEnzyme = []

for enzyme in enzyme_list:
    if 'NENZY' in enzyme:
        isEnzyme.append(0)
    else:
        isEnzyme.append(1)

In [68]:
all_data['isEnzyme'] = isEnzyme

In [69]:
all_data

Name  isEnzyme
0       ENZY1654         1
1       ENZY5484         1
2       ENZY6492         1
3       ENZY7850         1
4      ENZY16389         1
...          ...       ...
4995  NENZY20069         0
4996   ENZY10185         1
4997   ENZY20355         1
4998   ENZY20021         1
4999   NENZY1720         0

[5000 rows x 2 columns]

In [70]:
embedings = []


for enzyme in enzyme_list:
    word_embedidng = list(embeddings_per_enzyme[enzyme])
    embedings.append(word_embedidng)

In [71]:
len(embedings[0])

768

In [72]:
all_data['embedding'] = embedings

In [73]:
all_data

Name  isEnzyme                                          embedding
0       ENZY1654         1  [-0.117673, -0.5590602, 0.053475294, 0.2399229...
1       ENZY5484         1  [0.03548892, -0.8312112, -0.11381937, 0.778138...
2       ENZY6492         1  [0.12940304, -0.80807495, -0.2533453, 0.767868...
3       ENZY7850         1  [0.054603446, -0.85915095, -0.034092523, 0.626...
4      ENZY16389         1  [0.32245633, -0.52129877, -0.9004628, 0.688061...
...          ...       ...                                                ...
4995  NENZY20069         0  [-0.041115694, -1.052419, 0.31800702, -0.07281...
4996   ENZY10185         1  [-0.15134196, -0.73884666, -0.9098335, 0.39125...
4997   ENZY20355         1  [0.03483974, -0.6308391, -0.30230436, 0.307740...
4998   ENZY20021         1  [0.456246, -0.9279, -0.09795072, 0.8346221, 0....
4999   NENZY1720         0  [0.23149078, -0.72499555, -0.40589607, 0.20426...

[5000 rows x 3 columns]

In [74]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(all_data, test_size=0.2)

In [75]:
train

Name  isEnzyme                                          embedding
3920   NENZY9735         0  [0.31818533, -0.37694702, -0.0308326, 0.020454...
2555   ENZY15811         1  [-0.036135152, -0.74832034, -0.061013542, 0.79...
2083     ENZY692         1  [-0.3895061, -0.40527865, -0.6271133, 0.160577...
2792   ENZY20724         1  [-0.010716412, -0.7738669, -1.13077, 0.3598429...
3929    ENZY7008         1  [0.7006723, -1.1715786, -0.54822314, 0.1189138...
...          ...       ...                                                ...
1595    ENZY6772         1  [0.5147627, -0.45644826, -0.85519975, 0.106798...
3924    ENZY5852         1  [-0.53299046, -0.5891288, 0.42243943, 0.511998...
895   NENZY22168         0  [0.4280397, -0.6327227, -0.4627546, 0.52478606...
162   NENZY16945         0  [0.3472917, -0.7743673, -0.4503229, 0.3683932,...
1208   NENZY8215         0  [0.19026887, -0.9337723, -0.2935357, 0.4615156...

[4000 rows x 3 columns]

In [76]:
test

Name  isEnzyme                                          embedding
3212    ENZY7858         1  [-0.16904843, -0.5994134, -0.21337026, 0.30349...
3773  NENZY21490         0  [0.5303383, -0.43400624, -0.12761156, 0.255001...
4936   NENZY6504         0  [0.30268958, -0.70922565, 0.33324814, 0.015387...
4265   ENZY20068         1  [0.107869655, -0.97899324, -0.1415967, 0.42956...
1249   NENZY5062         0  [0.101537205, -0.47194064, -0.21013743, -0.146...
...          ...       ...                                                ...
73     NENZY1935         0  [-0.06490749, -0.10398245, -0.36084965, 0.2065...
2851  NENZY20047         0  [-0.10910252, -0.6647455, -0.27007523, 0.60354...
1737  NENZY11186         0  [-0.33059317, -0.79881203, -0.83117765, 0.3935...
3492  NENZY16157         0  [0.04108327, -0.8707555, -0.5172838, 0.0386886...
3166  NENZY11953         0  [0.4203817, -0.5538451, -0.769363, 0.7230054, ...

[1000 rows x 3 columns]

In [77]:
#Try KNN

from sklearn.neighbors import KNeighborsClassifier

In [78]:
neigh = KNeighborsClassifier(n_neighbors=3)

In [79]:
y = list(train['isEnzyme'])

In [80]:
X = list(train['embedding'])

In [81]:
neigh.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [82]:
x_test = list(test['embedding'])

In [83]:
y_pred = neigh.predict(x_test)

In [84]:
y_pred

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,

In [85]:
from sklearn.metrics import accuracy_score

In [86]:
y_true = list(test['isEnzyme'])
accuracy_score(y_true, y_pred)

0.808

In [87]:
from sklearn.ensemble import RandomForestClassifier

In [88]:
clf = RandomForestClassifier(max_depth=4, random_state=0)

In [89]:
clf.fit(X,y)

/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=4, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [90]:
y_pred = clf.predict(x_test)

In [91]:
y_pred

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,

In [92]:
accuracy_score(y_true, y_pred)

0.776

In [93]:
from sklearn.svm import SVC

In [94]:
clf = SVC(gamma='auto')

In [95]:
clf.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [96]:
y_pred = clf.predict(x_test)

In [97]:
y_pred

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,

In [98]:
accuracy_score(y_true, y_pred)

0.812

In [99]:
from sklearn.naive_bayes import GaussianNB

In [100]:
gnb = GaussianNB()

In [101]:
gnb.fit(X,y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [102]:
y_pred = gnb.predict(x_test)

In [103]:
y_pred

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,

In [104]:
accuracy_score(y_true, y_pred)

0.756

In [105]:
from sklearn.neural_network import MLPClassifier

In [106]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(X, y)

In [109]:
y_pred = clf.predict(x_test)

In [110]:
y_pred

array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,

In [111]:
accuracy_score(y_true, y_pred)

0.841